// src/utils/checklist.js
export const checklistItems = [
  { id: 1, text: "Existe copia de la documentación de validación" },
  { id: 2, text: "Tiene las placas de identificación correctamente colocadas y son legibles." },
  { id: 3, text: "El número de módulos y niveles se corresponde con el establecido en el documento de validación." },
  { id: 4, text: "Los niveles de altura están dentro de los límites establecidos." },
  { id: 5, text: "El tipo de puntal se corresponde con el del documento de validación." },
  { id: 6, text: "La verticalidad de los puntales está dentro de los límites permitidos." },
  { id: 7, text: "Las placas base no presentan deterioro y tienen todos los tornillos de fijación previsto." },
  { id: 8, text: "Las placas base no presentan descalce." },
  { id: 9, text: "La estantería no está fijada a otros elementos." },
  { id: 10, text: "La estantería no sirve de soporte a otros elementos." },
  { id: 11, text: "Los puntales no presentan deterioro." },
  { id: 12, text: "Las diagonales y horizontales de bastidores no presentan deterioro." },
  { id: 13, text: "El tipo de larguero se corresponde con el del documento de validación." },
  { id: 14, text: "Los largueros no presentan deterioro." },
  { id: 15, text: "Los largueros están montados horizontales y a la misma altura que el larguero opuesto." },
  { id: 16, text: "La flecha de los largueros está dentro de los límites establecidos en el documento de validación." },
  { id: 17, text: "Los largueros tienen puesto correctamente el dispositivo de fijación (horquillas)." },
  { id: 18, text: "No se aprecia en inspección visual grietas en soldadura o material base." },
  { id: 19, text: "Los elementos del sistema no presentan degradación por pérdida de pintura de protección y/o oxidación." },
  { id: 20, text: "El estado de las protecciones en el bastidor es correcto (mantienen distancia de seguridad y están correctamente fijadas al suelo)." },
  { id: 21, text: "Las cargas se ajustan a las dimensiones estandarizadas para las paletas." },
  { id: 22, text: "Las cargas a nivel de suelo no sobresalen de la alineación, respetando los anchos de pasillo." },
  { id: 23, text: "La iluminación es adecuada." },
  { id: 24, text: "En estanterías de picking las barandillas de segundo nivel están en perfecto estado, tienen pasamanos superior, intermedio y rodapié." },
  { id: 25, text: "En estanterías de picking se mantienen todos los elementos de los niveles previstos y en caso contrario se mantiene los largueros y/o baldas superiores y se ha señalizado correctamente 'no utilizar'." },
  { id: 26, text: "La carga se distribuye uniformemente y de forma ordenada." },
  { id: 27, text: "Las cargas están dentro de los límites establecidos en las placas identificativas." },
];